/* Generated By:JavaCC: Do not edit this line. ParserHurrConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserHurrConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DAY = 5;
  /** RegularExpression Id. */
  int MONTH = 6;
  /** RegularExpression Id. */
  int YEAR = 7;
  /** RegularExpression Id. */
  int HOUR = 8;
  /** RegularExpression Id. */
  int SIGNO = 9;
  /** RegularExpression Id. */
  int OCEANO = 10;
  /** RegularExpression Id. */
  int ESPACIOS = 11;
  /** RegularExpression Id. */
  int COMAS = 12;
  /** RegularExpression Id. */
  int LETRAS = 13;
  /** RegularExpression Id. */
  int NUMBER = 14;
  /** RegularExpression Id. */
  int TRACKEDENTRIES = 15;
  /** RegularExpression Id. */
  int PUNTOS = 16;
  /** RegularExpression Id. */
  int LAT = 17;
  /** RegularExpression Id. */
  int LON = 18;
  /** RegularExpression Id. */
  int RECID = 19;
  /** RegularExpression Id. */
  int STATUS = 20;
  /** RegularExpression Id. */
  int oceanID = 21;
  /** RegularExpression Id. */
  int namH = 22;
  /** RegularExpression Id. */
  int date = 23;
  /** RegularExpression Id. */
  int recordID = 24;
  /** RegularExpression Id. */
  int lat = 25;
  /** RegularExpression Id. */
  int lon = 26;
  /** RegularExpression Id. */
  int FILLCOLUMNS = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\" \"",
    "<DAY>",
    "<MONTH>",
    "<YEAR>",
    "<HOUR>",
    "<SIGNO>",
    "<OCEANO>",
    "<ESPACIOS>",
    "<COMAS>",
    "<LETRAS>",
    "<NUMBER>",
    "<TRACKEDENTRIES>",
    "\".\"",
    "<LAT>",
    "<LON>",
    "<RECID>",
    "<STATUS>",
    "<oceanID>",
    "<namH>",
    "<date>",
    "<recordID>",
    "<lat>",
    "<lon>",
    "<FILLCOLUMNS>",
  };

}
